[green_agent]
agentbeats_id = "019b4ca3-ef8b-7481-ab7c-1e5ce672152a"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}" }

[[participants]]
agentbeats_id = ""
name = "agent"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}" }

[config]
# The Agent Company benchmark configuration
# List the specific tasks to run in the assessment
task_names = [
  "pm-send-hello-message",
  "finance-qualified-bill-ask-for-reimburse",
  "hr-check-attendance-one-day",
  "pm-change-channel-ownership",
  "pm-add-new-moderator",
  "pm-update-sprint-cycles",
  "hr-check-attendance-multiple-days",
  "pm-schedule-meeting-1",
  "finance-nonqualified-bill-ask-for-reimburse"
]
